version: 0.2
phases:
  pre_build:
    commands:
      - set -e
      - echo $(date +%Y%m%d-%H%M%S) > /tmp/timestamp
      - echo $(cat /tmp/timestamp)
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m5k0g6n7
  build:
    commands:
      - docker build -t indigo_eln:$(cat /tmp/timestamp) .
      - docker tag indigo_eln:$(cat /tmp/timestamp) public.ecr.aws/m5k0g6n7/indigo_eln:$(cat /tmp/timestamp)
  post_build:
    commands:
      - docker push public.ecr.aws/m5k0g6n7/indigo_eln:$(cat /tmp/timestamp)
